# Generated by Django 4.2.11 on 2024-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0009_department_subject_subjectmarks_remove_grade_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmarks',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
